<?php
/**
 * Created by PhpStorm.
 * User: yuelin
 * Date: 2017/12/5
 * Time: 下午4:16
 */

namespace Linyuee;




class Wechat extends WechatBase
{

    public function __construct($appid,$secret)
    {
        parent::__construct($appid,$secret);
    }

    public function auth($redirect_url,$state = null){
            return parent::userinfo_auth($redirect_url,$state);
    }

    public function base_auth($redirect_url,$state = null)
    {
        return parent::base_auth($redirect_url,$state);
    }

    public function get_userinfo($code)
    {
        $auth_info = $this->get_auth_info($code);
        $user_info = $this->get_user_info($auth_info['access_token'],$auth_info['openid']);
        return $user_info;
    }

    public function get_js_sdk_sign($url){
        return $this->js_sdk_sign($url);
    }

    public function set_menu($menu)
    {
        return parent::set_menu($menu); // TODO: Change the autogenerated stub
    }

    public function pay($input,$key){
        return new WechatPay($this->appid,$this->secret,$input,$key);
    }




}